maucap20/poke-search

assets/js/script.js, index.html, mediumarticle.html, search.html
basic background of html created - henry
=> first commit

README.md
=> minor change on readme

pokemon-details.html
Worked on adding basic wireframes so that we can develop each parts.
=> basic framework for details tab

assets/js/script.js, assets/js/search-name-button.js, assets/js/search-type-button.js, index.html, pokemon-details.html
Inserted functions in (Search-name, Search-Type) to be relocated to pokemon-detail.html and a back-button that relocates users from the detail.html back to index.
=> Addition of functionality of buttons

README.md, assets/js/search-name-button.js, assets/js/search-type-button.js, index.html, pokemon-details.html
Created a README that meets the rubric requirements (has a unique name, description, technologies used, screenshot, and link to deployed application).
=> Add detail in README.md

assets/css/generalStyle.css, assets/css/reset.css, index.html, pokemon-details.html
Create general css stylesheet and have universal color variables,
=> Add stylesheets and link to html

assets/css/pokemon-details.css
1. Centered pokemon name
2. shifted back button to right.
* Figure out further: exactly center the pokemon name
=> Added header styles

assets/js/script.js, index.html
I added a button link to the html to call from the PokemonTCG API.
I added the necessary javascript to link the TCG API as well as get the information from the API to display on the index.html page.
=> added button to call from TCG API, added eventlistener to js

POC/POC-search-by-type.html
Creation of select button with all 17 pokemon types in the index.html under the input text. Added form sections within each input for later possible need for classification.
=> Addition of select button in index.html

assets/js/script.js, index.html
allows user to input a key word into a search bar and display first matching result from TCG API
=> add ability to search for certain pokemon

assets/css/pokemon-details.css, pokemon-details.html
Added base stats to the details page.
=> Added base stats styles

assets/js/pokemon-details.js, pokemon-details.html
Created fetch syntax(?) and added setPokeName function to it.
=> Replaced name section using API

assets/js/pokemon-details.js, pokemon-details.html
=> Added image using API

assets/js/script.js, assets/js/search-by-name.js, index.html
Console now logs name inputted. Possibly would need to create another issue as the submit button for name instantly logs you into the details page.
=> Search By Name Js created

assets/js/common.js, assets/js/pokemon-details.js, index.html
Adjusted the API fetch where all 1302 pokemon is shown instantly (from the first 20 of the last issue)
=> addition of the all entries into the table

assets/js/pokemon-details.js, pokemon-details.html
=> Added held item in Pokedex

assets/js/common.js, assets/js/script.js, assets/js/search-by-type.js, index.html
- open index.html
- note that the search results load when the page loads
- in the inspector, note the many (1302) console log lines. They indicate that the observer was attached to each search results row
- the lower number of calls to the stub function (26) are only for visible rows
- scroll down to observe that the stub function is called for each row that becomes visible
=> Intersection observer

assets/css/pokemon-details.css, pokemon-details.html
=> change style & implement mobile mode

assets/js/common.js, assets/js/pokemon-details.js, assets/js/script.js
- removed the console.log calls that occurred while loading the main page
- removed log() function from common.js because it was obscuring where the calls to log were coming from
- changed remaining calls to log() to call console.log()
=> 100 main page remove calls to consolelog while loading result

assets/js/common.js, assets/js/pokemon-details.js, index.html
Added firstLetterCapitalize() function to capitalize strings.
=> Added firstcase function

assets/js/pokemon-details.js, assets/js/script.js
Linking sucessful.
Hyperlinked each line, and tossed index data to local storage.
On details side, API is modified based on the call.
=> linked main page to detials page

assets/css/generalStyle.css, assets/js/script.js
able to sort through the pokedex on index.html by name with each keystroke.
=> 83 change search button to only affect index display
